version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: bookshelf_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: bookshelf_backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bookshelf
      - PORT=4000
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bookshelf_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
